sudo: false
language: go
cache:
 ccache: true
 directories:
    - /home/travis/toolchain

matrix:
  include:

  # Ubuntu
  - os: linux
    dist: bionic
    env:
    - MATRIX_EVAL="GOPRIVATE='github.com/libp2p/*' go get ./..."
    - LABEL="linux"
    - _DEPLOYABLE="true"
    - STRIP="strip"

  # Arm (aarch64) cross compile
  - os: linux
    dist: bionic
    env:
    - MATRIX_EVAL="GOPRIVATE='github.com/libp2p/*' go get ./..."
    - LABEL="aarch64"
    - _DEPLOYABLE="true"
    - STRIP="aarch64-linux-gnu-strip"
before_deploy:
- if [[ "${TRAVIS_TAG}" == "" ]]; then export TRAVIS_TAG=${TRAVIS_COMMIT} ; fi
- cd src
- TARGETS="go-karai"
- ${STRIP} ${TARGETS}
- rm -rf go-karai-${TRAVIS_TAG}
- mkdir go-karai-${TRAVIS_TAG}
- cp ${TARGETS} go-karai-${TRAVIS_TAG}/
- tar cvfz go-karai-${TRAVIS_TAG}-${LABEL}.tar.gz go-karai-${TRAVIS_TAG}/
- rm -rf builds
- mkdir builds
- cp turtlecoin-${TRAVIS_TAG}-${LABEL}.tar.gz builds
- cd ..

deploy:
  - provider: releases
    api_key:
      secure: MIGJAoGBAKY1mJtfyxF51Z8XSE4q/kLixEUegc4UGyP0lTH/URfJ3Yg7HzNwOXNg\nxWYtBWg8foI6H71J25iDGFYFA7ihY1GwDDlfd/RmYzBHD3nrVRdzYvvqKZgAfS9J\nvQnqfMVBRNYlP6osvgf394BvOTCrXh7WEQX6zLD0PO1wKgIEHhBzAgMBAAE=
    file:
      - go-karai-${TRAVIS_TAG}-${LABEL}.tar.gz
    skip_cleanup: true
    on:
      repo: karai/go-karai
      tags: true
      condition: "$_DEPLOYABLE = true"
